### ISSUE TITLE
Locking FFXIV ability to click anything after loading scaling

### ISSUE THREAD

**Issue by jolarini** [XIV-Tools/CustomizePlus#10]
hi, i understand this release had some hiccups but i'm not finding anybody with this specific problem atm..
i can't get my scaling to show up at all, when i import scale from Anamnesis and press save or save+close, it will either:
1. lock everything on ffxiv from being left or right clicked so i manually have to task kill ffxiv
2. not load the scale still, but make me unable to alt+tab or windows+tab away from the game so i have to close it through ffxiv

i am pretty sure i have the anamn scale up to date too

**Comment by SoloT4** [comment]
I'm having the same issue.

**Comment by jolarini** [comment]
hi again, sorry for the buffoonery. i just needed to switch to borderless windows + write in my characters name fully.
