### ISSUE TITLE
Character shrunken when transformed.

### ISSUE THREAD

**Issue by Kyraktos** [XIV-Tools/CustomizePlus#101]
I'm having a strange issue with scaling at the moment, I am experiencing my character shrinking whenever I am transformed. For example, the hacking mini-section in Tower at Paradigm's Breach - I am significantly smaller than everyone around me! I had the same issue on the second boss in Drowned City of Skalla, where you're turned into soot sprites. Also super tiny! 

I was able to narrow it down to CustomizePlus and the issue goes away whenever the plugin or my chosen scale is disabled. It's also visible to other users who are connected via Mare Synchronos. I am not sure if that helps narrow it down or not. Just having a scale applied (not edited at all) also causes the shrinking to occur.

I attempted toggling the "Apply to NPCS" and "Apply to NPCS in Cutscenes" which also didn't change anything with my character when replicating the issue. It's a pretty strange issue and I hadn't seen anyone talking about it anywhere yet aside from happening to myself, so I figured it was worth at least mentioning!

I've got a screenshot example here. Cheers!
![image](https://user-images.githubusercontent.com/131864809/234540799-f0d44f37-f9b0-4d26-a9cb-51448ae90c71.png)

**Comment by StoiaCode** [comment]
Will be fixed in the next release!
