### ISSUE TITLE
Nameplate and camera auto adjust

### ISSUE THREAD

**Issue by Grimskaldr** [XIV-Tools/CustomizePlus#104]
Newest update has caused the nameplate and camera adjustments for characters that are shorter or taller than the max height of their race.

**Comment by Grimskaldr** [comment]
It was working on the previous update, but after updating today, the nameplate is back inside my character's torso and the camera has reverted back to the default state.

**Comment by AlexCSDev** [comment]
The behavior introducted in the previous update was unintented bug. It's not supposed to function the way it worked in previous version because it breaks several visual features of the game.

**Comment by Grimskaldr** [comment]
Disappointing. I enjoyed not having my camera looking at my back and my nameplate in my chest.
