### ISSUE TITLE
NPC Tempest issues in shb zone

### ISSUE THREAD

**Issue by Megamustafa** [XIV-Tools/CustomizePlus#106]
In the Tempest, the plugin shrinks some ancients down to a normal size 
![ffxiv_29042023_234454_965](https://user-images.githubusercontent.com/123237389/235325444-b4e7260c-ee74-4de5-b798-83611d612a45.png)
![ffxiv_29042023_235021_884](https://user-images.githubusercontent.com/123237389/235325450-9aa073bb-e7e7-4588-bc27-9fe872083155.png)

I've attached 2 screenshots, one with Customize+ enabled, and one with Customize+ disabled 
Please fix this issue ASAP, thank you/

**Comment by StoiaCode** [comment]
It would help knowing what scales you have, since I cant reproduce it.
And then we will fix it when we find the time for it, and figure out whats causing it. 
Until then I will refer you to #84 seeing as this is most likely a root scale issue.

**Comment by Megamustafa** [comment]
I just installed for mare and didn't change any scales or any settings.

**Comment by StoiaCode** [comment]
Then idk what we can do, I cant reproduce it so I cant troubleshoot. We will see if we get other reports like this.
![grafik](https://user-images.githubusercontent.com/23234609/235325705-48ee7ac7-b271-4b66-941e-eb6b2ef0163f.png)

**Comment by Megamustafa** [comment]
![image](https://user-images.githubusercontent.com/123237389/235325757-30af969e-8e7e-4bf4-9563-06fd06bc0e6f.png)

these are my settings

**Comment by Megamustafa** [comment]
ah nvm i fixed it by unticking apply to NPCS
Thank you for your help i'll be closing this ticket
