### ISSUE TITLE
C+ not showing import character scale button

### ISSUE THREAD

**Issue by Allora02** [XIV-Tools/CustomizePlus#11]
Not exactly sure what I did wrong, as I've manually updated the repo to the new version on the wiki, but when opening the customize+ config tab, both using the chat command, and the button within dalamud plugins itself, the button to import anamnesis scaling and create characters is not shown. attached is a screenshot.
https://cdn.discordapp.com/attachments/867403322088620032/980885757961072721/unknown.png
also to confirm, dalamud does show that the plugin has been updated to version 0.0.0.6

**Comment by gucciBane** [comment]
I also have this issue and have just installed for the first time today (clean v0.0.0.6).

**Comment by Yuki-Codes** [comment]
can you verify the font options in dalamud settings?
![image](https://user-images.githubusercontent.com/379714/171085215-ff529bd2-c4f1-4892-b0cb-93953b62e10f.png)

**Comment by gucciBane** [comment]
I messed with the font scaling and styling.
[https://i.gyazo.com/0ec42265bc1f68f0f76bd6d13752ff62.mp4](url)

**Comment by Maxunit** [comment]
So yea, the font scaling breaks the UI. This happened with a good amount of plugins.

**Comment by StoiaCode** [comment]
Fixed
