### ISSUE TITLE
Bone physics of earrings when position altered

### ISSUE THREAD

**Issue by muuunnn** [XIV-Tools/CustomizePlus#110]
Shifted the position of the earring bones around, but only the models appear to have shifted properly. The physics of the models indicate that the bone itself has not moved and remains at its original position, because the models move via pendulum swing in relation to their original vanilla spot rather than where I shifted them. This resulted in a bouncy up-and-down earring rather than a swinging side-to-side motion.

**Comment by StoiaCode** [comment]
We cant fix the physics of the game just like that. 
So yeah this is a unlikely thing to ever change.

**Comment by muuunnn** [comment]
Not asking to alter the physics, asking about how it indicated that the bone itself hadn’t shifted.
