### ISSUE TITLE
Customize+ Scaling Breaks with Ktisis

### ISSUE THREAD

**Issue by w1ckr8396** [XIV-Tools/CustomizePlus#111]
Title. If you press the pose button in Ktisis while in gpose certain bones infinitely scale in a random direction. Did not have this issue with previous versions of C+ and Ktisis. Disabling C+ scaling instantly fixes the issue. Both my C+ and Ktisis are up to date.
![j0aWzE7](https://user-images.githubusercontent.com/42806886/236310702-e28b7185-713a-4ea3-806d-36a734153004.png)

**Comment by StoiaCode** [comment]
Intended, C+ is not compatible with posing modes. 
It also tells you so in a popup that you clicked away. 
We have no way of telling if Ktisis is active or not, once we do itll automatically deactivate, for now you manually have to do that.
