### ISSUE TITLE
Character Models Are Warping When It Has Position Value in the Customize Plus

### ISSUE THREAD

**Issue by xerxes-yelnos** [XIV-Tools/CustomizePlus#114]
Hello!

I would like to address this issue where C+ has this new implementation of adjusting our character position/rotation bones.
When I already have the stuff that I am happy with for my customization scales and position bones, an unexpected thing happened when I was trying to do Gpose in the game and it only happened in Gpose mode.

Here is the video example of the issue that I experienced:

https://streamable.com/6d3non

Note that this only happens when I try to use Gpose with Ktisis, but not with Anamnesis Poser.
Anamnesis Poser will reset my character position data to normal and also not stay as it is the scale+position bones that I have, while Ktisis has a major problem with the character bones keep warping out infinitely if I activate the Posing mode.

Probably this might have to deal with and work on together with Ktisis and Anamnesis?
I really hope that this issue can be solved soon.

Thank you!

**Comment by StoiaCode** [comment]
Customize+ is not compatible with posing mode in gpose. It disables itself once Anamnesis is turned on but we have no way of detecting Ktisis yet. 

It tells you this in a popup in game that you clicked away. 
There is no workaround.
