### ISSUE TITLE
Own Brute Justice massive in Rival Wings

### ISSUE THREAD

**Issue by D0t-Matrix** [XIV-Tools/CustomizePlus#116]
When Customize+ is enabled, the Brute Justice you are in gets scaled up significantly (2-3 times the height of the normal Brute Justice). This _appears_ to only impact the Brute Justice, and only impact the mech that you are in.

In testing on my machine, this has been isolated to Customize+ itself as the trigger for this behavior to happen, and the model does not scale back down once it's been scaled up without being un-mounted/killed/otherwise dispelled & re-entered.

**Comment by StoiaCode** [comment]
#118
