### ISSUE TITLE
Crashing on character swap

### ISSUE THREAD

**Issue by DingFandango** [XIV-Tools/CustomizePlus#12]
Whenever I log off one character to log into a different character on the same world (different races as well), the game crashes. I've been able to replicate it every time by logging in, logging out and logging into a different character.

**Comment by SkylerMews** [comment]
I've found where the exception occurs within the plugin, It seems to be an Access Violation within this `TryGetValue`:

```c#
if( CharacterToScale.TryGetValue( character, out var scale ) ) <--
{
	if( scale == null )
		return;

	scale.Apply( character );
}
```
