### ISSUE TITLE
Feature request Apply heels like float or sink when sitting option to counteract built in game chair sit float/sink

### ISSUE THREAD

**Issue by Kylis** [XIV-Tools/CustomizePlus#120]
When root scaled the "float" the characters normally get from the game is also scaled up or down such that when sitting you either end up floating above the chair if scaled up or in the chair if scaled down. Heels has stopped working as a band-aid to counteract this as they now have a sit check to make sure the heels settings aren't applied on sit but that leaves a gap that people are having to deal with. If this could be addressed within customize+ itself that would really be the best option.

**Comment by StoiaCode** [comment]
Refering to the first paragraph within #84

**Comment by Kylis** [comment]
Well I know but it is a thing with scaling in general, and I am basically looking for C+ to add the "sitting float" bone scaling. It is also noticeable with going through the normal racial scalings, just becomes a lot more noticeable with C+ not that it is a bug.
I figured if any plugin would be able to specify that specific value for adjustment it would be C+.
