### ISSUE TITLE
C+ disables mouse after importing Ana scaling file.

### ISSUE THREAD

**Issue by cait0** [XIV-Tools/CustomizePlus#13]
Completely fresh install. I type in the name of the character I want to apply C+ to, I click "Import scale from Anamnesis", I find the .pose and once I import I lose the ability to left click on anything.

**Comment by BigMunsBuns** [comment]
Same. Controller is functional after alt+tabbing back into the window but I cannot interact with the game or  Dalamud overlay at all.

**Comment by campbebj** [comment]
Friend is having the same issue, and another person mentioned it on the discord, just letting you guys know its still happening, is there any known workaround?

**Comment by StoiaCode** [comment]
Is this still happening?

**Comment by TiamatKefir** [comment]
This is still happening, yes.

**Comment by BigMunsBuns** [comment]
It doesn't lock a controller from being used, though. If you play with one, previewing fullscreen or windowed should then restore mouse functionality.

**Comment by StoiaCode** [comment]
Im looking into swapping from the Windows Explorer to the Dalamud Explorer, that may help with this. We will see.

**Comment by StoiaCode** [comment]
This should now be fixed? Reopen if it occures again despite the new Explorer
