### ISSUE TITLE
Positioning and Rotation functions interact strangely to Anamnesis and Ktisis

### ISSUE THREAD

**Issue by Ultrapyre** [XIV-Tools/CustomizePlus#133]
While the fixability of this particular issue might be debatable, it might be worth mentioning: the positioning and rotation functions doesn't play nice with Anamnesis and Ktisis.

In the case of Anamnesis, enabling any of the edits (rotation, position and scale) overrides whatever edits were done via customize+. This might not be as noticeable with only scaling edits, but with rotational edits enabled in Anamnesis's posing mode by default enabling pose mode has the potential to scrunch up the character like an aluminum can when the rotations snap back to default, and the same applies to positional and scaling edits when those are enabled in Anamnesis too. Perhaps there are temporary workarounds, but until someone brings mention to said workarounds I have to bring this up as an issue.

As for Ktisis, it would seem that the customize+ edits are being applied accumulatively when ITS posing mode is enabled. As a test, I rotated a singular body part by 1 degree, and when posing mode is enabled only that body part in particular began to spin continuously on the spot as if it were attached to a motor (and it spins faster with larger degrees of deviation too!) Needless to say, turning on the posing mode when rotation and position edits are all over the body results in what can only be described as an explosion of limbs....

That about sums up the issue. Until those are fixed, more elaborate gposing with customize+ edits is a considerable challenge, so I'd appreciate whatever can be done about this.

**Comment by dendr01d** [comment]
Did you perchance see this warning message? The measures described therein are indeed the best workarounds we have implemented at the moment, but it's possible we'll have something better working in the future.

![image](https://github.com/XIV-Tools/CustomizePlus/assets/10487419/c7cc83e4-8680-441c-a29d-fd1a0170a691)

**Comment by StoiaCode** [comment]
Fixed with new update.
