### ISSUE TITLE
Customize+ Unintentional Interaction With P12S Phase 2 Mechanics

### ISSUE THREAD

**Issue by Marvolose** [XIV-Tools/CustomizePlus#134]
(P12S Phase 2 mild spoilers within)

In P12S Phase 2, the boss uses an ability called Gaiaochos, which applies the Ascension debuff that is supposed to make your character small, like with the Mini status effect. However, at the moment Customize+ overrides this effect and your character is full size during the mechanic.

**Comment by Theo-Asterio** [comment]
This also happens with any debuff that forcible changes your size. However I've found a work around. Disable the C+ plugin. Then in %appdata%/Xivlauncher/pluginConfigs in your CustomizePlus.json you need to find the scale(s) you're using and remove the entry for root. not root (blah blah), but root. Once you do that for all applicable scales, the debuffs will work appropriately.

**Comment by StoiaCode** [comment]
Will be fixed in #123 this version.
