### ISSUE TITLE
Characters return to normal size during "shrink" mechanic of p12s p2

### ISSUE THREAD

**Issue by EdelgardXIV** [XIV-Tools/CustomizePlus#147]
P12s P2 has a mechanic that shrinks the player, and limits their movement. With a C+ scaling applied, on first GCD after being shrunk the player returns to their normal size, but movement is still limited. The larger player sizes makes completion of the mechanic much more difficult. 

Tested with disabling all mods (penumbra) first, no change. Then disabled C+ as well. Issue resolved. Re-enabled mods, issue still resolved, finally turning C+ back on brings the above behavior back. I also have video to show if helpful.

**Comment by StoiaCode** [comment]
Known issue, fixed in the rework luckily. If you feel adventures you can try the testing version.

**Comment by EdelgardXIV** [comment]
testing this tonight, will let you know. test version will be v0.0.2.2

**Comment by EdelgardXIV** [comment]
confirmed fixed in v0.0.2.2, no issues in p12s p2.

**Comment by EdelgardXIV** [comment]
issue seen again in main version v0.0.2.5

**Comment by StoiaCode** [comment]
Known, will be fixed in the next release! Sorry!

**Comment by StoiaCode** [comment]
Should be fixed now? Closing, pls reopen if not.
