### ISSUE TITLE
Cannot Resize Edit Window

### ISSUE THREAD

**Issue by Shrimbop** [XIV-Tools/CustomizePlus#148]
Hi there, 

On my Dalamud, the edit window is extremely thin and I can't see anything to be able to edit. Re-sizing the window doesn't help. Any ideas? 
<img width="1277" alt="Screenshot 2023-06-29 at 11 20 31 AM" src="https://github.com/XIV-Tools/CustomizePlus/assets/67430754/06e31f42-6d75-45ef-bbfa-9b0b5510a12b">

**Comment by StoiaCode** [comment]
that looks unusual, what does Resizing do if it doesnt help? Does it not resize at all?

**Comment by StoiaCode** [comment]
Closed due to inactivity.
