### ISSUE TITLE
Player character scale modifies all player preview windows in Doman Mahjong

### ISSUE THREAD

**Issue by Otaku-2** [XIV-Tools/CustomizePlus#152]
Can be seen easily with face modifications.

**Comment by StoiaCode** [comment]
Screenshots would help a lot here as someone that never even touched Mahjong

**Comment by Otaku-2** [comment]
Control image of my character's face with eyes scaled up, eyebrow inner positioned up, and lip left/right rotated up.

![image](https://github.com/XIV-Tools/CustomizePlus/assets/21027484/d47c3883-0536-4e66-a826-9f57764e4369)

Image of someone else's char in Mahjong with the scalers that are set to be used by my char.

![image](https://github.com/XIV-Tools/CustomizePlus/assets/21027484/29d4e3e6-3264-489c-b7e3-3ca6abd187d7)

Seems to be placing my PC scale on everyone else's char in the previews in Mahjong, also places my scales on their Adventurer Plates before the game starts.

Dunno if it matters, but using Glamourer, I can see that the game just uses 4 differently-named models to do the character previews. (janky workaround squeenix)

![image](https://github.com/XIV-Tools/CustomizePlus/assets/21027484/22ade13e-5c89-4727-af3a-b33479fdabd3)

This, in order, is:

Character Screen - your pc
Examine Screen - character to your right
Fitting Room - character across
Dye Preview - character to your left

**Comment by StoiaCode** [comment]
Yeah the part about the Adv. Plates is known. The Mahjong things probably use the same technique and will be fixed when we get around to fixing the adventure plate would be my guess. Thanks for reporting!

**Comment by StoiaCode** [comment]
I added this to #84 so will close this for consistency, thanks again!
