### ISSUE TITLE
Scaling in cutscenes removed with the new update?

### ISSUE THREAD

**Issue by MaelstromFalco** [XIV-Tools/CustomizePlus#157]
Hello!

I may have missed the patch notes that said this was happening, but was there a reason why scaling in cutscenes were removed with this update or was this an oversight?

I'm new here and I do I like this addon. I'm not trying to be rude and I'm thankful for the work you are putting in. I'm just curious as to why this option is gone.

**Comment by StoiaCode** [comment]
Known issue, we are attempting to find a fix! Still thanks for reporting!
