### ISSUE TITLE
overall scale values missing since update. Changing any values causes the rest to disappear; bones lost from memory. Other profiles not working at all.

### ISSUE THREAD

**Issue by wishmaker11** [XIV-Tools/CustomizePlus#158]
![image](https://github.com/XIV-Tools/CustomizePlus/assets/77934951/e7cd6d8f-9c56-4801-92f2-babf9e711188)
Honestly don't even know what to say about this one. Was working fine yesterday but today it did this. Once this happens the editing file is corrupted and can't be edited again once closed, so the only option is to delete.

**Comment by StoiaCode** [comment]
Is this scale for a player character? Whatever it is make sure it's present and the name is correct.

If the editor window doesn't open back up disable and enable the plugin in dalamud settings, then it'll pop back up.

**Comment by wishmaker11** [comment]
> 

Yes it is. I have deleted and remade multiple attempts for the same character, with everything present and written correctly, and disabling and reenabling the plugin doesn't stop the issue. It also doesn't stop the fact that changing any of the values completely breaks the plugin.

**Comment by StoiaCode** [comment]
Can I get you to post a /xllog?

- Restart game
- Trigger bugs in C+
- Open log
- press copy to clipboard button in the top left
- paste in here, preferably in a codeblock or even in a text file.

**Comment by wishmaker11** [comment]
Unfortunately(?) since the update I haven't been able to recreate the bugs. Even though I'd restarted the game and the plugin several times last night prior, and haven't done anything out of the ordinary.

The function to scale my entire character up and down is still missing though. Was that removed?

**Comment by StoiaCode** [comment]
welp if its gone its gone, Ill consider that good! 

If you just want to use it to scale your char, then yes. Use Penumbra Racial scaling for that, https://twitter.com/oftheholybooty/status/1576278166309830657?t=TWoOm8cPVN4wfez8Kerz-g&s=19

If you want to use it elsewhere (only if you have to) you can unlock it in the settings, top right the Cogwheel, and in the advanced tab.

I will close this here, feel free to reopen if it happens again!
