### ISSUE TITLE
Scaler Falls Off Within Gpose

### ISSUE THREAD

**Issue by Aminthea** [XIV-Tools/CustomizePlus#16]
I'm not sure if this is intended or not for the scaler to persist while in gpose, but at first launch of the new release, it did just that. The scale would persist in gpose and animations would be function with the scale added onto any character. However, with a few weeks passing and the most recent update of Anamnesis, the scale now drops when entering gpose and reverts the character back to whatever size they were before.

I'm not sure if this is an intended feature, or just a bug I experienced for some time- but I do like having my scaling be persistent when entering gpose and I'd like to know if this is an issue that can be fixed or if its a feature that can be persistent. Thanks ♥

**Comment by Maxunit** [comment]
This is a known bug right now and the latest source code has a fix for it.
The current build, 0.0.0.6, has a cache for storing those changes and it has some issues.
The latest code changes remove this cache and have fixed those issues you mentioned.

If you are familiar with compiling code yourself, then building C+ from the latest github code will fix those issues.

**Comment by Aminthea** [comment]
I'm not familiar with compiling code, sadly. I might have to just wait then. :(

At least I'm safe knowing its a known issue!! And not like an accidental feature I stumbled upon or something lol.

**Comment by StoiaCode** [comment]
#84
