### ISSUE TITLE
scaling not reflecting in cutscenes since update

### ISSUE THREAD

**Issue by eliasmorganclark** [XIV-Tools/CustomizePlus#160]
hey y'all, just wanted to pop in and log this - ever since the update was applied to Customize+ today, my fiancée and i are noticing that scaling is now no longer applying in cutscenes, as well as when examining each other's  character models. it is working in the normal game and with mare, tho.... 

for reference, we are doing the endwalker role quests and have not tested this in any other cutscenes as of this time.

**Comment by zakz** [comment]
It's not working in previous cutscene neither. Ma partner got shrink back in ARR level 35 cutscene.

**Comment by StoiaCode** [comment]
Known issue and already tracked in #84 

Will leave this open for discussion tho.

**Comment by Phenrei** [comment]
This is addressed for named scales [here](https://github.com/XIV-Tools/CustomizePlus/commit/320a6d4ed4594f29af2f0a8d03b2661324e08d22). I determined "Default" is globally broken on the player during this testing, including during cutscenes, so it will have to be a player-named scale specifically, but it will now work into cutscenes from fixing the old check we did on the relevant object ids.
