### ISSUE TITLE
No bone scaling option

### ISSUE THREAD

**Issue by GigiIsADreamer** [XIV-Tools/CustomizePlus#163]
Hi there, I recently installed Customize+ and tried using it, however I seem to be missing features. It wont show bone data or let me scale anything. I compared with a friend and their UI window is totally different from mine. I've tried it with and without advanced options selected, I checked to make sure the plugin was up to date, and nothing worked.
Can someone please tell me why this may be happening and how I can fix it? This is my window:
![ffxiv_07212023_225201_124](https://github.com/XIV-Tools/CustomizePlus/assets/140223152/b8fd61ec-ff64-457d-81a4-56596e48ccf9)
This is theirs:
![image (3)](https://github.com/XIV-Tools/CustomizePlus/assets/140223152/6de9b394-3b70-48b0-ac87-0c1717c6fa31)

**Comment by decoytrix** [comment]
It is hit and miss for me. Sometimes I would get Root back with toggling "Show Live Bones" on that last picture.  I spent a good couple minutes toggling that and the root enabling option itself. And toggling the plugin itself from the /xlplugins installer menu when the plugin wasn't responding all that well.

**Comment by GigiIsADreamer** [comment]
Hmm I just tired to toggle that option a bunch of times, and remade the profile and tried more, still nothing showed up. :c

**Comment by StoiaCode** [comment]
Follow these steps please: 

1. open /xllog 
2. Click the Trash Icon at the top row to clear the log
3. uninstall C+ (you wont loose and profiles)
4. install C+
5. attempt to Create/Edit this scale that shows no bones
6. open /xllog again and hit the Copy Icon
7. Paste it into a Text File and attach that Text file here.

**Comment by StoiaCode** [comment]
Closed due to Inactivity, reopen if the issue persists.
