### ISSUE TITLE
Root scaling height and nameplates

### ISSUE THREAD

**Issue by decoytrix** [XIV-Tools/CustomizePlus#164]
I was surprised to see this happening when I had a taller character. I used to edit character height through penumbra, using a mod that was just sliders under the Advanced Editing->Meta Manipulations menus, and with that the nameplate and camera shifted up a bit as if I were playing a taller race. 

![nameplate bug](https://github.com/XIV-Tools/CustomizePlus/assets/15527419/8e74e1ba-b4a3-44fb-a113-220f8b258657)

**Comment by StoiaCode** [comment]
Height and nameplate dont scale with root. 
Keep using penumbra for this, that's the intended way.
