### ISSUE TITLE
Mod UI changed and I cant find how to change my character's overall size

### ISSUE THREAD

**Issue by KelsBee** [XIV-Tools/CustomizePlus#167]
Help please I only use this mod to make my lalafell 10 stories tall to take funny screenshots and now I cant do that

**Comment by StoiaCode** [comment]
https://twitter.com/oftheholybooty/status/1576278166309830657?t=TWoOm8cPVN4wfez8Kerz-g&s=19

**Comment by KelsBee** [comment]
seems like a real pain in the ass to the way it was before. Wont this method also affect other male lalafell?
