### ISSUE TITLE
[Feature Request] Adjust Bone Positions -edit-

### ISSUE THREAD

**Issue by corvusv** [XIV-Tools/CustomizePlus#17]
One of the things I do alongside scaling is I edit the positions certain bones to make them less scrunched up and uncanny.

i.e) if i scale waist/leg/calves/feet up to 1.15 in Ana, i use position on the feet to bring them further down so they aren't squished into the calves. If i want to make a character's tail larger, I need to add to the X-axis to push the bones further apart so that it's longer

or if I want to create wider thigh gap, I'll change the position of legs on the Z-Axis in Ana

I noticed that when I saved those changes alongside scaling in an Anam pose, it only loaded the scaling. Is this a bug, a planned feature eventually or would it not work/break animations? I have no idea because the position changes seem to all be relative, so I thought it might work but i have 0 experience outside of posing

**Comment by Maxunit** [comment]
Only scaling is supported. Positioning and Rotation can only be done in GPose while the actor is frozen.

**Comment by corvusv** [comment]
If it's even possible, I'd like it to be a feature. One of the things about editing the scale of a PC's body that makes it look kind of odd is the fact that once you do so, the bones remain in the same spot. If you scale certain parts up to even relatively low amounts, like calves, they clip into your feet and delete your ankles. Same thing happens with breasts, especially on certain outfits, and it essentially makes rescaling your tail impossible because you can't make it longer as a result of not being able to do that.
