### ISSUE TITLE
Scaling profiles deleted on next bootup after a duplication.

### ISSUE THREAD

**Issue by MaelstromFalco** [XIV-Tools/CustomizePlus#172]
The way this bug happens is that after a profile is duplicated, the original profile is deleted upon the next bootup of C+. 

The only workaround I can find is to duplicate the profile twice. Change one of the duplicates as much as you like and leave the other duplicate the same so it can be used as backup in case the original profile is deleted.

**Comment by StoiaCode** [comment]
This should be fixed in the new release. Closing this, feel free to reopen if not.
