### ISSUE TITLE
Profiles deleted

### ISSUE THREAD

**Issue by Flemps** [XIV-Tools/CustomizePlus#174]
First time logging onto FFXIV in a while, and I come to find that the profile i normally use is deleted? I found it on the legacy .json, but despite trying to change it to match the current version (albeit, sloppily) i can't get it to load. Is there any way to more easily import legacy profiles?

**Comment by StoiaCode** [comment]
Just move the Customize.json and the Customize folder away, then rename the legacy to just the name of the config file. 
Do all that while the game is closed ofc, then start the game and itll convert it.

**Comment by StoiaCode** [comment]
Closed due to Inactivity, reopen if the issue persists.
