### ISSUE TITLE
Scale reverting

### ISSUE THREAD

**Issue by Adr3x** [XIV-Tools/CustomizePlus#176]
I know its patch day, but usually don't have this issue, even though my scale is enabled, my scale keeps reverting back to "normal" whenever I change zones and also going into Gpose...then I have to reapply the scale again, and doing so this last time it wasn't accepting me clicking on any of the scales, nothing would change...I had to turn C+ off and back on....but that didn't solve the reverting problem

**Comment by StoiaCode** [comment]
Can you reproduce this and then check /xllog and see if it says anything? Preferably set the xllog to "Debug" before via the little cog icon in the window that appears when you type /xllog.
