### ISSUE TITLE
Profiles Resetting Upon Launch

### ISSUE THREAD

**Issue by Bupernox** [XIV-Tools/CustomizePlus#177]
I noticed not long after the 6.45 patch that my Customize profile would reset upon booting the game, and I have to now manually re enter the numbers in the profile every time I play.

On a related note, when I go to edit a profile by hitting the button to bring up the bones sub menu it resets every value all over again. It's like it refuses to save the values I last entered.

**Comment by StoiaCode** [comment]
Can you reproduce this and then check /xllog and see if it says anything? Preferably set the xllog to "Debug" before via the little cog icon in the window that appears when you type /xllog.

**Comment by Bupernox** [comment]
Is there anything in particular I should be looking for in the log?

**Comment by Bupernox** [comment]
![log](https://github.com/XIV-Tools/CustomizePlus/assets/141894639/80863d9d-37c3-438c-a477-961326676df0)
So I deleted my profile and the plugin, went to reinstall it and got this in the debug log.

**Comment by Bupernox** [comment]
Is there any way to fix or change the config path, assuming it's the only issue?

**Comment by Bupernox** [comment]
I dunno if this helps at all, but while I can see my own scaling other players cannot. I assume that's because it's just storing a preview and can't actually save the scaling data because the path is invalid?

**Comment by Bupernox** [comment]
Oh hang on, I managed to fix it. I deleted my profiles, deactivated C+, deleted the config folder, and uninstalled C+.
I then went into the Experimental tab of Dalamud and deactivated the Sea of Stars plugin that gave me C+, saved and closed, then reactivated it and reinstalled C+. Now it's saving my profiles :D
