### ISSUE TITLE
Scales not showing

### ISSUE THREAD

**Issue by mechabunbun** [XIV-Tools/CustomizePlus#178]
I've been using this for months without an issue, but I recently got a new computer and ever since I can't get my scales to show up. But, my friend can still see the changes done to my character through mare, they just don't show up on my end. 
The only changes I've made are to make my character a bit more slender, and I haven't touched anything to do with root or height or anything else.

**Comment by StoiaCode** [comment]
1. Did you make sure your Character name is writtten EXACTLY right?
2. make sure in the settings the "Enable" checkbox is checked
3. Is this in general, or does this only happen in specific edge cases? 
4. Can you try to create a scale in game, by creating a new one and then clicking the Pen Icon to open the edit window and sliding things around?

**Comment by mechabunbun** [comment]
I have done all of the above several times over, since first noticing this issue. I triple checked that my name was written correctly, and that the box was enabled. I tried making a new scale several times and slid stuff around, both by making a new from scratch and by trying to import from anamnesis. And every time I couldn't see any changes on my end, while my friend could see them be updated through Mare. 
I've tried to troubleshoot this on my own for the past two weeks, and I honestly can't think of anything else that I can do that I haven't already tried. I even imported others' scales just to see if they would do something, and nothing happened. And every time I always made sure that my character's name was written correctly and that it was enabled. 
This also happens in general. Since getting my new computer, C+ hasn't worked once. I never had trouble with it on my old computer, which is why I'm so stumped as to what to do. I've tried running everything as administrator too, and I've double checked that everything is whitelisted from my anti-virus programs, just to rule out anything else it could be. 
I'm sorry if I wrote this in a confusing way, since english isn't my first language >< but thank you for any help!!

**Comment by StoiaCode** [comment]
Can we get a log? 

### Basic Debuglog
- Open /xllog in-game
- Click the cogwheel and put Log level to Debug.
- Clear the log using the button in the log window
- Reproduce the issue
- Copy the log file to clipboard from the /xllog window and paste it into notepad, save the file
- if the game hard crashes copy the dalamud.log from %appdata%\xivlauncher\
- Attach the file to Discord by drag+dropping it into the Discord client
- Change Log Level back to Information unless further requested

**Comment by mechabunbun** [comment]
I tried doing a couple things here, like changing the sliders and making a new profile. Hopefully this helps!

[DBG [CustomizePlus].txt](https://github.com/XIV-Tools/CustomizePlus/files/12368220/DBG.CustomizePlus.txt)

**Comment by OfficialVannt** [comment]
I'm having this exact same problem.

**Comment by orenji** [comment]
This is happening to me as well as two other friends. When I go into gpose, my custom scaling looks as it should, but those of my friends gets reverted to default. When they gpose, their character looks fine but anyone else gets reverted to default.

**Comment by mechabunbun** [comment]
I should emphasize again that the issue I'm having is that Customize doesn't work at all. 
I am making changes to the sliders for my character, see no changes happening on my end for my character, while my friend sees the changes happening on my character since we have mare linked for each other. 
But at no point ever do the changes that I make to my character appear on my screen. C+ just doesn't work ever for me, and yet it does since the changes are clearly being made as my friend can see them.

**Comment by RigzGx** [comment]
I wonder sometimes if Bibo+ is actually the culprit

**Comment by droth-dreynor** [comment]
I have the same issue. Sometimes C+ does apply stuff, sometimes it does not, friends can often still see the changes via Mare while I myself can't. Sometimes clicking on "edit" and closing the scale helps, sometimes it just completely breaks and nothing I do brings back my scale. I ONLY encountered this issue in the "newer" version of Customize+ where you can scale everything individually but apparently not just my character globally anymore. Which is actually the only thing I would want from it, so I don't want to throw that profile away - is there still a way to do that? I just want to scale my catboy by a certain value to have my character be my irl height, and well, everything should scale with it.

**Comment by StoiaCode** [comment]
@droth-dreynor https://docs.google.com/document/d/1lzxG85hjYKNWwXrVJn79jk2E1xXD0pG5_k6Ep2zGZWc/edit#heading=h.16nnbr4e7wue

**Comment by mechabunbun** [comment]
I want to start this by saying that I know this is a lot of work, and I do appreciate all of the time and effort that is put into this plugin! 
It's been almost two months soon, and I still have this problem of my character being unaffected by any changes made with C+, but it still shows on my friend's end. Even with all the newest updates and everything. 
I don't want to be pushy as all I want is for my character to just be a bit more slender and that's all. (No, I **don't** want to make my character taller or smaller. That is not the issue) 
I do want to mention that I tried using C+ on several of my other characters now, always making sure their names are spelt correctly, and it never works. I've also tried disabling all my mods and to run C+ as the only plugin. 
But yeah, I know these things take time, and I know my issue seems to be rather odd, so I just wanted to clear up some misunderstandings I've seen in the comments and explain further what other things I've tried in the past month. 
Maybe I'm just cursed ahaha

**Comment by mechabunbun** [comment]
I am not entirely sure when it happened or which update might have fixed it, but when I tried to disable and enable the "Enable Profiles" option today, C+ suddenly worked like it should again. 
https://gyazo.com/c68139d3ca391a2584de73967386ef1b
I know for a fact that I've tried doing this before, and it didn't work then, but I won't complain :)
