### ISSUE TITLE
Profiles being deleted upon launch

### ISSUE THREAD

**Issue by Fangbanger** [XIV-Tools/CustomizePlus#179]
Recently when I launch the game the profile i had set to a character will be gone and a different profile will be activated. For example- a profile for editing the size of miqo ears when using a specific ear mod will be deleted; but a different profile for changing the size of the vanilla ears will be active (making the ear mod look huge since it is the wrong profile). It is not just ear scales but that was an example. I noticed this issue when I added a second character for scales - but did not previously have the issue when i had a character profile and a minion profile (roughly when the last patch dropped).

The profiles for the new character were made using the 'duplicate profile' function and then renamed to the new character. The scales typically all edited the ears eyes and chest - though other profiles using those same scales are unaffected. 

The profile names did contain special characters (+) but others using the same special characters were unaffected..

The characters were from different home worlds.

The Only Owned function was not enabled on any profile.

Thank you for your time

**Comment by StoiaCode** [comment]
Sounds like #172 
Will have to look into that, for now try to avoid using the Duplicate function.
