### ISSUE TITLE
C+ not appearing over Mare when others are in GPose

### ISSUE THREAD

**Issue by muuunnn** [XIV-Tools/CustomizePlus#180]
In a group of people all synced through Mare, when others enter GPose my character is the only one whose C+ edits do not show up. Others all reported that the other characters in our party all showed properly with the C+ edits.

I have tried disabling, uninstalling, editing the scaling and closing and saving, removing the party members from my friend list, reloading Mare, etc. but we can't figure out why specifically my character does not show. I saw on previous mentions in the Discord server that C+ must be enabled on NPCs but I can't find the option to checkbox anywhere, has it been changed, and is it relevant at all to this issue?

**Comment by StoiaCode** [comment]
#159
