### ISSUE TITLE
Root Scaling gone ?

### ISSUE THREAD

**Issue by lambprey** [XIV-Tools/CustomizePlus#183]
With the recent update, with all the bones being organized differently; Root scaling has essentially disappeared from the plugin entirely. 
My old settings for characters who were scaled with the root slider are still saved, but I can no longer scale anything else this way because the feature has been taken out of the plugin.
I do not see this as a known issue, but myself and quite a few others are wondering what happened to Root Scaling ?

**Comment by StoiaCode** [comment]
Intentional, use Penumbra Racial scaling for Full Character scaling. 
In the settings you can enable it again to remove it from your current scales, or non-height scaling related things.
