### ISSUE TITLE
Customize+ scaling not showing up on my character

### ISSUE THREAD

**Issue by yuukiwi** [XIV-Tools/CustomizePlus#189]
hello! i typically do not mess with customize+ as i have already made a scaling i love for my character, but i was recently trying to help a friend figure out how to get a preset scaling to work and switching between profile's and editing another. now my scaling does not show up for me at all on my end but shows up perfectly fine via mare. i have tried restarting the game multiple times, enabling/disabling the plugin itself, uninstalling/reinstalling the plugin, and enabling/disabling the profile. my character's name is written correctly and i have tried creating multiple new profiles, imported scales, and tried sliding the values around to no avail. i'm just at a total loss as i have tried to browse around the xiv tools discord and the issue section here and have seen no clear answers or fixes regarding this issue though it seems to be a recurring problem. any help would be incredibly appreciated, thankyou!

**Comment by StoiaCode** [comment]
Sounds like #178 

If you are already are on the discord, follow the debug protocol posted in the issue linked above and slide with the log into my DMs please. 
I will close this here, further discussion in the other issue.
