### ISSUE TITLE
Feature Request: Relative Positioning for Bones

### ISSUE THREAD

**Issue by StinkingRabbit** [XIV-Tools/CustomizePlus#190]
Currently, when positioning bones using Customize+, they move along axes based off of the bone’s original position and orientation. However, in Anamnesis, bones are positioned based off of their parent bone. I doubt the values Anamnesis uses come from the tool itself, and rather can be found in-game, so I don’t think it’s impossible for a toggle of sorts to be added to switch between the current positioning and a positioning similar to Anamnesis. Of course, I don’t know what the code for this or FFXIV looks like, so this request may end up being unreasonable.

**Comment by StoiaCode** [comment]
What you're asking for is essentially parenting, or at least part of parenting as far as I can see it. Which is something that's planned but not for the near future :)
