### ISSUE TITLE
Issue with scaling while in Gpose

### ISSUE THREAD

**Issue by JunnieJ** [XIV-Tools/CustomizePlus#192]
For a while now, I've had an issue with friends who scale their bodies being reverted while in gpose. Everything was working fine until it wasn't, and I'm not entirely sure how to resolve this. 

![2023-09-12_10-49-04-530_OkamiGameplay](https://github.com/XIV-Tools/CustomizePlus/assets/144815446/46b6e37a-3c02-4c8d-989e-6aafef0e462b)
![2023-09-12_10-49-12-576_OkamiGameplay](https://github.com/XIV-Tools/CustomizePlus/assets/144815446/1178eaea-85c1-4c79-95c5-01ed5282100f)

**Comment by StoiaCode** [comment]
Known, fixed in testing but will take a bit to ensure stability
