### ISSUE TITLE
Tail Scaling reverting with certain emotes and cast animations

### ISSUE THREAD

**Issue by LuceAeton** [XIV-Tools/CustomizePlus#196]
This doesn't seem to be an issue for anything but the tail.
I've found that white Mage, Scholar, and Astro casts break it. But Sage does not.
Black mage also breaks it! But SMN and RDM do not. 
Some emote examples are: squats, push-ups, sit ups, ground sit (all), chair sit (but only the two newest sit poses)

I turned off penumbra to rule out mods breaking it. It did the same with the vanilla tail. So unsure if it's just me or something about the tail bones. 
My tail is scaled on the X axis. With only tail C and tail D changed. 
This might be an unavoidable issue but I didn't see anything on it so I thought I'd post here!

**Comment by maramouch** [comment]
I have the same issue, super obvious when I /joy with my Miqo'te
