### ISSUE TITLE
Customize+ UI isn't displaying correctly for my friend.

### ISSUE THREAD

**Issue by devorixiv** [XIV-Tools/CustomizePlus#20]
![customize plus screen 1](https://user-images.githubusercontent.com/110715700/183239414-8347d4e1-5313-4e12-b019-712d4077032f.png)
![customize plus screen 2](https://user-images.githubusercontent.com/110715700/183239417-d5f24eda-4573-43de-b917-12744248c185.png)

FIrst screen is my UI, second screen is my friend's. They just installed the plugin and appear to not have any option to add lines for new characters. Not sure what's causing it, or why their screen looks different from mine.

**Comment by Phenrei** [comment]
Looks like they're using a non-default style, there's a whole customization for that hidden under Dalmud Settings > Look & Feel > Style Editor. Have them save a copy of theirs and reset back to a default (or copy yours, there's a tool to import/export to clipboard) and see if they still have the issue. Various alignment/scale/etc settings in there could break it, it's a very basic UI.
