### ISSUE TITLE
C+ applying to random people not synced with

### ISSUE THREAD

**Issue by eranarana1** [XIV-Tools/CustomizePlus#203]
I've been having an issue for a couple weeks, that persisted through a reformat, where other people's C+ scaling is applying to people not in the syncshell or synced with me, I can provide a couple screenshots and logs if needed, but its like a flickering happening every few minutes sometimes to multiple people at once, sometimes isolated to one person regardless of fem/masc.

**Comment by Xehanort09** [comment]
Same here its dropping my fps by a good 20 the moment I turn customize on and I just see people flicker.

**Comment by eranarana1** [comment]
small update it is now applying random people's c+ scaling to people in the same syncshell as well, not just unsynced/vanilla people

**Comment by MeikoXIV** [comment]
Problem is still occuring. it even seems there are same "presets" that apply to random person, upon pairing up it just affects another person (?) now I can see 3 people like that at once though.

**Comment by StoiaCode** [comment]
This is fixed in the testing release which is a full rework.
