### ISSUE TITLE
C+ not loading in gpose

### ISSUE THREAD

**Issue by Hex-Healer** [XIV-Tools/CustomizePlus#206]
Hi! So up until the patch today this wasn't an issue, and I'm not sure if it's a me issue or an actual issue issue so I figure I'll plop this here and hope for the best!
Since today when I load into gpose, people I'm synched withs C+ no longer loads. I was trying to take photos for a friend and every time I loaded up gpose it would revert her back to vanilla scaling.
I'm not sure whats going on! If it is a me issue please correct me, thank you!

**Comment by StoiaCode** [comment]
That has been the case for a while now.
Get their scale localy or get a MCDF.
