### ISSUE TITLE
No Overall Scale Option

### ISSUE THREAD

**Issue by Sansflaire** [XIV-Tools/CustomizePlus#209]
There used to be an option to scale the whole model equally, but it appears to not be possible anymore.

**Comment by Allora02** [comment]
This is intentional. Height scaling/full model scaling should be done with penumbra racial scaling mods, and not with cutsomize+. There is a guide pinned in the discord showing how to do so.

**Comment by Sansflaire** [comment]
> This is intentional. Height scaling/full model scaling should be done with penumbra racial scaling mods, and not with cutsomize+. There is a guide pinned in the discord showing how to do so.

Does that apply to minion/fairy/carbuncle etc? Because the Root option under Advanced works on my character, but not other types of models.

**Comment by TheRedScythe38** [comment]
You mentioned a discord, where can I find it to utilize this guide. I also just think it was an overall stupid decision to remove the full body scaling option.
