### ISSUE TITLE
Made my Au Ra taller but now camera focuses on her chest in cutscenes

### ISSUE THREAD

**Issue by NebNeb890** [XIV-Tools/CustomizePlus#214]
my char lore is that she's half elezen half au ra so i used C+ to make her taller, but sometimes in cut scenes it will zoom on her chest instead of her face. this isnt every time, but enough times to potentially ruin story beats. is there a way to fix this? ive been told i could use a fantasia to change the ingame race to a taller race like elezen or viera, but that would change the in game dialog and ruin immersion;;

**Comment by Allora02** [comment]
The way to fix this is by using penumbra racial scaling mods instead of c+. C+ is not meant to be used for height for pretty much this exact reason.
