### ISSUE TITLE
Height scaling causes inappropriate nameplate and camera placement

### ISSUE THREAD

**Issue by LongTimeNoSiege** [XIV-Tools/CustomizePlus#22]
Because Customize+ only uses bone scaling and not character data scaling, when changing height with Customize+, the height of the camera and nameplate of the character are unaffected. This can make it difficult to see your character when zoomed in with shorter height, and cause your head to clip through your nameplate with taller heights. When height is scaled via character data (on the character tab of Anamnesis or Textools racial settings) the camera and nameplate placement are also adjusted, but bone scaling via Anamnesis' poser or Customize+ does not affect those two things.
I assume this is already a known issue and will be fixed if it's possible to implement character data scaling in future updates, but I'm mentioning it just in case someone else has this problem. As of right now the only way to circumvent it that I know of is to disable the Customize+ height scaling and use Textools or Anamnesis to scale height instead.

**Comment by StoiaCode** [comment]
Not planned as of right now.
Special Snowflake exists for simple height scaling.
