### ISSUE TITLE
"Download Failed" on Plugin Installer

### ISSUE THREAD

**Issue by jxmey** [XIV-Tools/CustomizePlus#23]
So I've had Customize+ on Dalamud for a few months now and I haven't had any problems with it at all. Yet, in the past few weeks or so, I've been getting errors whenever I close out of FFXIV from Dalamud, saying one of my plugins is causing problems. It didn't seem to do anything game breaking, so I just left it. After a bit, Dalamud actually told me what was causing problems, and it says it's because the download failed for the CustomizePlus github link for some reason? Yet, despite this, Customize+ still works and there hasn't been any actual issues with my gameplay, but it's still making me a bit nervous. Attached are images to show what I mean.

![image](https://user-images.githubusercontent.com/70993079/185783167-d6bcf824-79d2-45a8-a264-6edfeba98ce0.png)
![image](https://user-images.githubusercontent.com/70993079/185783187-b20cd82a-f307-450b-9e21-6d3e9d53b9b6.png)

**Comment by Phenrei** [comment]
Repo has been moved to https://raw.githubusercontent.com/XIV-Tools/DalamudPlugins/main/repo.json

Delete your existing copy of the plugin, remove that old repo, and add the new one, 6.2 update coming very soon.

**Comment by ryukoko** [comment]
> Repo has been moved to https://raw.githubusercontent.com/XIV-Tools/DalamudPlugins/main/repo.json
> 
> Delete your existing copy of the plugin, remove that old repo, and add the new one, 6.2 update coming very soon.

I have done this and noticed nothing appears when i search for C+ in the plugins list, is this due to not being updated for 6.2 yet?

**Comment by AikoTM** [comment]
Had the same issue already before 6.2
Could only find it in the plugin list with the old repo.

**Comment by ThaddeusCleaver** [comment]
Also echo-ing this. Still not seeing it even after deleting the old one and adding the new repo link.

**Comment by Maxunit** [comment]
Customize+ has been updated for 6.2, code-wise, but the update has not been pushed yet as far as I know.

**Comment by Phenrei** [comment]
Sorry for the delay, as the code was available but I was unable to finalize a push. Additionally, there was an issue with the repo structure as Punchline was missing, this has been fixed.

**Comment by jxmey** [comment]
I apologize for responding to a thread that's already closed, but just like the others above, I'm unable to find Customize+ in the plugins after deleting the old repos. I'm assuming that the update was pushed considering the response above by Phenrei, but apologies if it's still not out yet! Thank you for your time!

**Comment by Phenrei** [comment]
Make sure https://raw.githubusercontent.com/XIV-Tools/DalamudPlugins/main/repo.json is in the list and enabled, and that the old files are removed. Dalamud seems to have some issues if you "orphan" a plugin's files if you have deleted a repo for, so you may have to go into %AppData%\XIVLauncher\installedPlugins\CustomizePlus\ and clear it out fully. It may also take a game restart for Dalamud to properly refresh the repo list.

Going to re-open as the transition will definitely be causing some issues for people, but it is resolved if you set it up correctly, for myself and others on the discord.

**Comment by jxmey** [comment]
Oh wow, yeah! Clearing out the Customize+ folder from my %AppData% actually did the trick! Thank you so much, Phenrei, I appreciate the time you took to respond to this thread!
