### ISSUE TITLE
Support for Mare

### ISSUE THREAD

**Issue by ffxivthruple** [XIV-Tools/CustomizePlus#27]
Hello!! was just wondering if there is a possibility that CustomizePlus will support Mare Synchronos?  Or maybe I am doing something wrong but the scaling doesnt show for those that i am paired with on mare.

Thank you very much!!!

**Comment by Maxunit** [comment]
There's currently no interaction possible between Customize+ and Mare Synchronos. It might be a feature at some point.

**Comment by ffxivthruple** [comment]
Thank you so much for your response!! Also, thank you for your amazing plugin!!!

**Comment by FFXIVRP-Developer** [comment]
I was just about to ask this same thing. It'd be fantastic to not need to re-scale every single piece of gear in mods and just use this to edit our characters for everyone,
Are there any donations accepted to push certain features forward?

**Comment by Allora02** [comment]
At the moment, there is no donation box to prioritize features. The api for mare integration is being considered, but will NOT be worked on until the most basic features are stable. There is currently a UI rework in progress, along with bugfixes that need to be completed before an API can be started. 
If you would like this to be completed faster, you can either help the dev with pull requests fixing the previous bugs listed in the github threads, or create the API for mare yourself, and send that in as a pull request.
