### ISSUE TITLE
Scaling not applying to Carbuncle?

### ISSUE THREAD

**Issue by gcomp90** [XIV-Tools/CustomizePlus#29]
Hello, thanks for the hardwork getting CustomizePlus compatible for 6.2!

Post update I'm having issues applying scaling to characters imported on Carbuncle. I'm able to apply and save scaling to myself and edit it. But typing 'Carbuncle' under the name like it was for the prev. patch does not seem to apply any scaling that I save to the character. It also does not let me edit it at all. I tried typing Carbuncle a few different ways, but I'm unsure if I'm doing something wrong or if it is a current issue. 

Thanks for your time!

**Comment by Phenrei** [comment]
I removed root scaling on BattleNpcs (which Eos/Selene/Carbuncle are) and didn't include an exclusion for player-owned ones. Just figured out a good workaround for that after seeing this issue, it will be part of next update.

**Comment by gcomp90** [comment]
Awesome thanks so much for your time in responding, much appreciated. :)
