### ISSUE TITLE
[Feature] Scales for every specified race

### ISSUE THREAD

**Issue by Roxxies** [XIV-Tools/CustomizePlus#31]
Could it be a possibility in the future to apply a scale for everyone that uses a specific race?

**Comment by Lockehart** [comment]
To add onto this, possibly a way to set for only males or females too.

**Comment by Kinzon** [comment]
Bringing this back up, being able to do something like applying a scale to all hrothgar would be nice.

**Comment by StoiaCode** [comment]
#84
