### ISSUE TITLE
[Feature] Anamnesis-style muscle slider

### ISSUE THREAD

**Issue by atikabubu** [XIV-Tools/CustomizePlus#32]
Could it be possible to have a muscle slider like in Anamnesis that goes from nothing to way-too-much like in Anamnesis? The current mods that add some beef to ladies have the problem that they're way overblown on max muscle slider (the game one), and both T&F and B+ have the muscles a bit too soft for my liking. A slider in C+ would be a great way to fine tune the values above what the game allows without resorting to extremes.

**Comment by Maxunit** [comment]
The muscle slider belongs to the "Extended Appearance" feature set from Anamnesis and that is currently not supported by Customize+

I am not 100% sure right now, but I think such features are planned, but need additional work.

**Comment by atikabubu** [comment]
Closing this up since Pallete+ has this feature now (and also YAB+ is a thing now)
