### ISSUE TITLE
UI scale

### ISSUE THREAD

**Issue by qohqoh** [XIV-Tools/CustomizePlus#34]
![image](https://user-images.githubusercontent.com/107040809/191425561-f06f27e7-21e1-4c4f-af35-af8e9a7f52f5.png)
cannot see whole options in large font

**Comment by Maxunit** [comment]
That is a known issue and needs to be fixed somehow at some point. You'd have to temporarily switch to a font scale of 9.6pt or 12pt whenever you want to change something in Customize+
