### ISSUE TITLE
Caravans UI bug

### ISSUE THREAD

**Issue by NovaNami** [XIV-Tools/CustomizePlus#36]
I have been experiencing the "Caravans" bug in the UI where some symbols turn into Caravans. It has persisted with restarts. 

![image](https://user-images.githubusercontent.com/117041633/198900033-a634e3f2-8922-4a4a-b099-14acbd6ec206.png)

I have heard that this is a known bug with Imgui? Customize+ is the only plugin where I have this though.

**Comment by StoiaCode** [comment]
Should be fixed by now? Reopen if not.
