### ISSUE TITLE
Tail not showing up

### ISSUE THREAD

**Issue by zhizhigezh** [XIV-Tools/CustomizePlus#40]
I'm  a miqo'te female and there is no option to change my tail, my friend has it and she is able to change her tail in multiple ways but no matter what i try there is just no tail options for me, tried uninstalling and reinstalling, restart game, change races, add new character, i even tried installng extra bones/skeleton

**Comment by miqolena** [comment]
Seconding this, another user with a fresh install of Dalamud and Customize+ as of 1/16/2023 could not see tail options as an Elezen female to change my (Miqo'te fem) tale.

**Comment by StoiaCode** [comment]
Can you send the .pose used when importing please?

**Comment by miqolena** [comment]
That's the thing, we're not importing ana poses - the TailA - TailE nodes simply aren't there to modify on my friend's screen when using Edit Body Scale (WIP) mode.

**Comment by StoiaCode** [comment]
Ah. Well yeah then just import a scale from and that is saved with a tail, then it should work

**Comment by SamuelHSmith** [comment]
Getting this on my Hrothgar as well. I'll try the import method.
