### ISSUE TITLE
[Feature Request] Apply unique customizations for specific Gear pieces on the same Character

### ISSUE THREAD

**Issue by ZambehTV** [XIV-Tools/CustomizePlus#41]
Proportions on body mods and custom clothing sometimes ends up being different from the proportions of your character's base model  (or each other) and causes noticeable discrepancies when compared to the rest of your gear. This is especially noticeable when you compare vanilla gear to modded/fitted gear.

Because of this, I was wondering if it would be possible to implement a feature where you could select a specific piece of gear and apply changes to your customize+ profile when wearing it. That way, users could manually make changes to the proportions of these pieces to be more in line with the rest of the character.

**Comment by ivalith** [comment]
I'd also like to request this as with more body types being made and mods typically being fitted to one or two types, it would be extremely convenient to be able to have custom scales that apply to specific equipment, similar to the way the xlheels plugin offers a list of gear to specify an adjustment to (though I know this would obviously be more complex). Custom scaling is probably my favorite feature we've been given through plugins and the increase in bodies that alter different body parts so much makes it really hard to have one single scaling that works across everything for a character.

**Comment by StoiaCode** [comment]
#64 and #84
