### ISSUE TITLE
Permanently Messed up Camera Position

### ISSUE THREAD

**Issue by BunBun22** [XIV-Tools/CustomizePlus#44]
After i got rid of Customize Plus i noticed that my camera is too high and i don't know how to revert it. Uninstalling the plugin didn't do anything i was using it with cammy.

**Comment by Maxunit** [comment]
Your Camera should reset to default values if you delete any presets in Cammy or delete Cammy itself.

Customize+ shouldn't be able to mess with your camera settings.

**Comment by StoiaCode** [comment]
Closed due to no further comment.
