### ISSUE TITLE
"Scale import from Anamnesis" button doesn't works for me

### ISSUE THREAD

**Issue by Taddam3** [XIV-Tools/CustomizePlus#47]
Scale import from Anamnesis button doesn't works , when I choose one of the pose file and click open ,I'm stuck there I can't open or close anything and there is windows beeping sound everywhere I click and nothing more

**Comment by Megalodork** [comment]
I am experiencing the exact same issue, too

**Comment by LynxPi** [comment]
If it helps changing from fullscreen to borderless windowed did the trick for me

**Comment by Revenwyn** [comment]
That button literally does not even show up for me.

**Comment by StoiaCode** [comment]
Lower your font size a bit, that should make it show up

**Comment by StoiaCode** [comment]
Hopefully fixed in the newest update; Reopen if not.
