### ISSUE TITLE
Plugin apparently decommissioned

### ISSUE THREAD

**Issue by lolaluwu** [XIV-Tools/CustomizePlus#52]
ever since the 6.3 patch i am unable to use customize+. it is saying that it is either decommissioned entirely or simply just out of date. all my other plugins updated just fine but only this one seems to be missing and i dunno how to fix it.

**Comment by lolaluwu** [comment]
i do have the correct link already. i disabled all other repositories i happen to have to be extra sure, but it is still saying that it is an unknow repository

**Comment by lolaluwu** [comment]
it doesn't even let me simply just delete it. it is only letting me shedule it

**Comment by StoiaCode** [comment]
Yes you need to restart between Addon deletions when theres crash potential. Its a Dalamud savety feature. Please send a pic of your repositories.

**Comment by lolaluwu** [comment]
yea, after deleting it and opening the game a day later it updated and nabbed the current version of the plugin. thank you. ♪

**Comment by Kekmono** [comment]
I'm having a similar issue where Customize+ just stopped working. I've tried reinstalling it and unchecking Automatic Mode and fiddling with every setting and nothing. I figured it would fix itself if I just left it alone and went to bed like OP mentioned, but the problem persists.

**Comment by Allora02** [comment]
please see the previous answers. you have an outdated repo link, and need to delete the old plugin and link, then put in the new one after restarting

**Comment by Kekmono** [comment]
Is this not the correct repo link? I thought it was
![mspaint_2023-01-25_16-49-14](https://user-images.githubusercontent.com/115731847/214709714-8ba119c5-175e-4394-a450-3f61d7a494a5.png)

**Comment by Allora02** [comment]
that does appear to be the correct repo link. are you sure you disabled/deleted the plugin before swapping repo links? mine does not say decomissioned on it, and that usually means you have an outdated repo

**Comment by Kekmono** [comment]
After deleting the folder itself using %AppData%\XIVLauncher\installedPlugins and making sure EVERYTHING was disabled and then deleted and re-doing the repo link it started working after I deleted my "Characters:" and added a new one with my exact name
![ffxiv_dx11_2023-01-25_17-07-09](https://user-images.githubusercontent.com/115731847/214712692-2d729763-6b68-421c-bac4-9dc7f224b103.png)

**Comment by Allora02** [comment]
interesting. it shouldn't have required that level of removal, but i guess that the old character info was still hanging onto the old repo and freaking out dalamud. glad it got fixed at least.

**Comment by StoiaCode** [comment]
Fixed
