### ISSUE TITLE
Download resets at a certain point and never completes

### ISSUE THREAD

**Issue by JulianaIsSalty** [XIV-Tools/CustomizePlus#54]
I was cleaning plugins and accidentally had deleted it. I copied the link and attempted to redownload it, only to be told the total memory of dalamud and plugins, resetting again and again and never finishing the download.

**Comment by Phenrei** [comment]
You may have abandoned files in the folder where the download is attempting to go. Make sure no CustomizePlus files live in Dalamud's plugin folder in AppData, then hard remove the repo (don't just uncheck the box), restart the game, re-add the XIVTools repo link, and then reattempt the download. If you still have issues after the post-restart state where there was no file in the folder and no plugin in the available to install list, you'll probably have to check on the Dalamud discord for additional help.

**Comment by JulianaIsSalty** [comment]
Thank you! How do I access these folders and delete them? I'm sorry, I'm not the most tech savvy person ;;

**Comment by StoiaCode** [comment]
Did this ever get resolved?
