### ISSUE TITLE
Scale preset save location?

### ISSUE THREAD

**Issue by AikoTM** [XIV-Tools/CustomizePlus#55]
Apparently you can't ask in any discord for help for this plugin, so I'm sorry if i miss-use this GitHub.

I loaded in a scale from Anamnesis and changed it with the scale editor of Customize+.
I then saved it under a new name… However, I cannot for the life of me figure out where it got saved to or even if it does get save somewhere as a file that can be imported again. 

So my question is… Where does C+ save the scale presets you make with its own scale editor? 

Again, sorry.

**Comment by StoiaCode** [comment]
Don't have a response because it's Hella late but: discord https://discord.gg/xivtools

**Comment by AikoTM** [comment]
See, I thought I was in that discord, but couldn't find it anymore.
Thanks :3 I'll ask there.

I guess this can be deleted.
