### ISSUE TITLE
[Feature Request] executing /customize > exit customize

### ISSUE THREAD

**Issue by seirralanzce** [XIV-Tools/CustomizePlus#58]
I hope this is not too much, but other plugins allow me to on and off by using same command calling it, so hoping customize can also do same as i place it in macro to press buttons to pop it out and off.

**Comment by Maguillage** [comment]
I assume them mean using the /customize chat command to open the menu.
Unlike most plugins, doing /customize a second time doesn't currently close the menu.
Personally I figured it was just an alpha build quirk that would sort itself out eventually.

**Comment by seirralanzce** [comment]
yes sorry, i meant to open and close the UI window when executing the command again.

**Comment by StoiaCode** [comment]
Implemented the function in my local build. Waiting for some other things to go through, then if nothings missing and if I didnt mess up I hope it will come with the next update :)

**Comment by seirralanzce** [comment]
> Implemented the function in my local build. Waiting for some other things to go through, then if nothings missing and if I didnt mess up I hope it will come with the next update :)

is it put as save and close as well?

**Comment by StoiaCode** [comment]
No, since that would be covered by Auto mode saving once you do changes instantly. If you knowingly disabled that option, only pressing save will save, nothing else. And I dont think it should be otherwise.
