### ISSUE TITLE
Weapon Scaling (Main and Off-hand) don't seem to work with C+

### ISSUE THREAD

**Issue by Syuqaa** [XIV-Tools/CustomizePlus#6]
Body scaling works perfectly fine for me in C+, however when I try to scale the weapons of my character (Both Main and Off-hand), there seems to be no change in C+.

Specifically, I am trying to increase the size of the shield for PLDs by modifying these two bones in Anamnesis:
"**Shield (Left)**" bone (_Unsheathed shield_)
"**Oh_n_hara**" bone (_Sheathed shield_)

I also tried to modify the Mainhand weapon size (Just to check), but ran into the same problem

**Comment by StoiaCode** [comment]
#84
