### ISSUE TITLE
IVCS Buttocks isn't working right

### ISSUE THREAD

**Issue by Kurai-Wolf** [XIV-Tools/CustomizePlus#60]
I have the whole IVCS thing set up and used Anamnesis originally to import a body but when I put clothes on only the buttocks setting goes to vanilla. And if I go into the ingame editor for customize+ I notice the buttocks isn't an option. So now i'm just kinda stumped because everything else saves and changes correctly.

**Comment by StoiaCode** [comment]
Clothing needs to support the extra IVCS bones, else it wont reflect the scaling of them. Nothing C+ can do about bones not existing on that piece of clothing.

**Comment by Kurai-Wolf** [comment]
Damn OK, do you know why when I open the ingame editor it resets the buttocks? It doesn't seem to do that to any of the other IVCS only scalings. Thank you for the help o/

**Comment by StoiaCode** [comment]
Hmmm, this shouldnt happen. Can you reproduce it still, 100% of the time?
