### ISSUE TITLE
Character size not changing under normal in-game conditions (i.e. status effect Minimum, etc.)

### ISSUE THREAD

**Issue by totallyskelebones** [XIV-Tools/CustomizePlus#61]
When inflicted with the status effect Minimum, which changes the character's size (like Cerberus in World of Darkness, purple orbs in Syrcus Tower, the SB A rank hunt Sum, etc.), the camera will move as normal to show the player's smaller size, but the actual character model will not change size. For me, this is consistent across all instances of character-shrinking debuffs. I have not tested whether this also occurs for effects that make the player larger (Dohn Mheg 2nd boss), though since there's far fewer of those.

Currently the only scaling I have Customize+ doing is increasing the Root for my character to 1.032. I have Automatic Mode and Apply to NPCs enabled as well.

**Comment by StoiaCode** [comment]
#84
