### ISSUE TITLE
scale being applied to other players instant portraits

### ISSUE THREAD

**Issue by utterablevenus** [XIV-Tools/CustomizePlus#66]
with 6.3 introducing portraits popping up at the start of duties, ive noticed some look kinda off when i play a specific character. after a while i realized its because her personal scale is being applied to them randomly. i have apply to npcs/npcs in cutscenes turned off and it still happens

**Comment by StoiaCode** [comment]
#84

**Comment by SerraBritt** [comment]
I don't know how helpful this might be, but my friend and I did some testing and it is applied explicitly to portraits 3, 4, and 5. 
![image](https://user-images.githubusercontent.com/131739401/234178796-45be0f1b-6a9a-46a5-8abc-31b1d9f16fa0.png)
My friend made their character extra wide so we would see if it was just the camera moving or the entire scale and this was the result. Their character was changed as expected, but other portraits were not expected to change. These three portraits are the ones that are always changed and it doesn't appear to be random.
