### ISSUE TITLE
6.1 Compatibility

### ISSUE THREAD

**Issue by Yuki-Codes** [XIV-Tools/CustomizePlus#7]
Customize+ is not yet working with 6.1.

Looks like the render hook signature is wrong somehow, it hooks successfully, but the callback is never called.

**Comment by Yuki-Walsh** [comment]
@LunNova can you take a look at the signature?

**Comment by LunNova** [comment]
I'm really busy right now and haven't been playing, so not sure if I'll get to it soon. :(

**Comment by Yuki-Walsh** [comment]
Looks like the signature is correct, but the method for OnRender is wrong somehow. the hook is attaching, but is never called.

**Comment by LunNova** [comment]
Nice!
