### ISSUE TITLE
[Feature Request] /customize [CUSTOMIZATION NAME] [TARGET]

### ISSUE THREAD

**Issue by GunB** [XIV-Tools/CustomizePlus#73]
Would love to have a command to assign the customization I'd like by using macros to make the process simple just like penumbra does it.

Their command is:

```
Use with /penumbra collection [Collection Type] | [Collection Name] | <Identifier>
》 Valid Collection Types are Base, Ui, Selected, Individual, and all those selectable in Character Groups.
》 Valid Collection Names are None, all collections you have created by their full names, and Delete to remove assignments (not valid for all types).
》 If the type is Individual you need to specify an individual with an identifier of the form:
》》》 <me> or <t> or <mo> or <f> as placeholders for your character, your target, your mouseover or your focus, if they exist.
》》》 p | [Player Name]@<World Name>, if no @ is provided, Any World is used.
》》》 r | [Retainer Name]
》》》 n | [NPC Type] : [NPC Name], where NPC Type can be [M]ount, [C]ompanion, [A]ccessory, [E]vent NPC, or [B]attle NPC.
》》》 o | [NPC Type] : [NPC Name] | [Player Name]@<World Name>.
```

It'd be incredible to change what customization to use with a macro and combine it with other macros to easily change characters on the fly by the click of a button

**Comment by GunB** [comment]
I tried to use this new feature with <me> instead of Character name but it didn't work. Am I using it wrong? If <me> or <self> is not supported, would it be possible to support it? This way the macros would be only one instead of one per character

**Comment by StoiaCode** [comment]
Can you open /xllog and show us what it says when you try it with those commands? I have no idea how these are translated, I have a suspicion why they dont work, but that would help!

**Comment by GunB** [comment]
![image](https://user-images.githubusercontent.com/3722960/235312297-0d092819-199d-4558-906b-5f19b8091d5f.png)

**Comment by GunB** [comment]
Also would it be possible to instead of having the Scale assigned to a character, just replace the name of the owner of the scale so they are re-usable?

**Comment by StoiaCode** [comment]
Not entirely sure what you mean by that?

**Comment by StoiaCode** [comment]
Wait but <self> is not a valid tag, <me> is

**Comment by GunB** [comment]
So right now the macro works as a toggle. If the Scale exist for X character then the macro turns it on. My suggestion would be to instead of being a toggle, use the macro to replace the name of the character assigned to the Scale, so that way Scales are reusable among other characters by using the macro.

**Comment by GunB** [comment]
![image](https://user-images.githubusercontent.com/3722960/235312568-cff4a821-1573-4cd1-ae81-7fcab3c2fa2c.png)

**Comment by StoiaCode** [comment]
> So right now the macro works as a toggle. If the Scale exist for X character then the macro turns it on. My suggestion would be to instead of being a toggle, use the macro to replace the name of the character assigned to the Scale, so that way Scales are reusable among other characters by using the macro.

No sorry, while obviously possible _changing_ things via Commands is not something I'd want, at least not in that format. Just duplicate that scale and give it that other characters name. We COULD allow a placeholder as character name entirely, but that would require a check. Cant say at the top of my head how much work it would be.

As for the log, thank you! Its about as I expected, will have to look at how Chat handles the tags then and implement that.

**Comment by GunB** [comment]
> > So right now the macro works as a toggle. If the Scale exist for X character then the macro turns it on. My suggestion would be to instead of being a toggle, use the macro to replace the name of the character assigned to the Scale, so that way Scales are reusable among other characters by using the macro.
> 
> No sorry, while obviously possible _changing_ things via Commands is not something I'd want, at least not in that format. Just duplicate that scale and give it that other characters name. We COULD allow a placeholder as character name entirely, but that would require a check. Cant say at the top of my head how much work it would be.
> 
> As for the log, thank you! Its about as I expected, will have to look at how Chat handles the tags then and implement that.

A placeholder would work too, I really wouldn't mind it. Some clothes need different scales so it's really annoying to change manually and with different characters. I would REALLY appreciate it. 

Thank you so much for at least considering it. And Thank you for checking into my < me> issue.

**Comment by StoiaCode** [comment]
For the clothing its planned to sometime have conditional application instead of just names, like youd see with XLHeels. That is still along way out though.

**Comment by GunB** [comment]
> For the clothing its planned to sometime have conditional application instead of just names, like youd see with XLHeels. That is still along way out though.

This would also work for those who want to show different characters with different scales. Like having "Glamourer Alts" instead of having a brand new character. It's not only clothes but totally different characters as well.
