### ISSUE TITLE
Height scaling not working.

### ISSUE THREAD

**Issue by MissMarakar** [XIV-Tools/CustomizePlus#82]
On installing the latest update  (v0.0.1.5), I shrank back to base height.  Customize+ doesn't seem to be factoring overall height scaling from the .pose file anymore.

**Comment by StoiaCode** [comment]
You should be able to scale the root bone just as before, try setting it again in the edit window.

**Comment by MissMarakar** [comment]
Yep, that helped fix it up.  For some reason, even the original .pose file dropped it somehow.  More on Anamnesis than here.  Thank you!~
