### ISSUE TITLE
Command already registered

### ISSUE THREAD

**Issue by Kurochi51** [XIV-Tools/CustomizePlus#83]
This error pops up when loading the plugin, included full unload/load snippet of log.

> 2023-04-21 02:07:52.675 +03:00 [INF] [LOCALPLUGIN] Unloading CustomizePlus.dll
> 2023-04-21 02:07:53.682 +03:00 [INF] [LOCALPLUGIN] Finished unloading CustomizePlus.dll
> 2023-04-21 02:08:04.136 +03:00 [INF] [LOCALPLUGIN] Loading CustomizePlus.dll
> 2023-04-21 02:08:04.251 +03:00 [DBG] [CustomizePlus] Initializing c+ ipc providers.
> 2023-04-21 02:08:04.252 +03:00 [DBG] [CustomizePlus] Initializing legacy c+ ipc providers.
> 2023-04-21 02:08:04.371 +03:00 [DBG] [CustomizePlus] Hooking render function
> 2023-04-21 02:08:04.372 +03:00 [DBG] [CustomizePlus] Sending c+ ipc scale message.
> 2023-04-21 02:08:04.374 +03:00 [DBG] [CustomizePlus] Sending legacy c+ ipc scale message.
> 2023-04-21 02:08:04.374 +03:00 [ERR] Command /customize is already registered.
> 2023-04-21 02:08:04.375 +03:00 [INF] [LOCALPLUGIN] Finished loading CustomizePlus.dll

**Comment by StoiaCode** [comment]
Correct, it currently does. That should have no impact on the plugin actually running tho, correct?

**Comment by Kurochi51** [comment]
Indeed, there should be no impact, I just thought I'd report the bug.

**Comment by StoiaCode** [comment]
Known, still thank you!
