### ISSUE TITLE
Tail rotation and position functioning differently after game restart

### ISSUE THREAD

**Issue by IminhaK** [XIV-Tools/CustomizePlus#85]
Discovered the rotation and position features last night and changed my tail bones to be sticking upwards by adjusting the Roll on both Tail A and Tail B, and couldnt get tail C D or E to do anything no matter what wild numbers I had entered in. Every time i was rotating A, B-E also seemed to inherit this rotation which helped a ton in getting the result I wanted. Same occured for B, causing C-E to also inherit the rotation. After opening my game this morning, tail is no longer sticking up the the rotations i applied are no longer being inherited by lower parts of the tail and just created messed up twisted bones.

I'm not sure if this is a feature request or issue or both.

Issues:
customizations did not behave the same after restarting game and can no longer replicate the original behavior

Feature Request?
Allow bones to inherit rotation/position so that for example tails or arms can be moved all at once instead of having to move each part individually which might require a lot of effort to get a realistic result.

Image of previous and current behavior with the same rotation and position edits
Previous and desired behavior:
![image](https://user-images.githubusercontent.com/6138413/233704074-ea9f8c53-b843-4e0d-a164-32f3100d3631.png)
Current behavior:
![image](https://user-images.githubusercontent.com/6138413/233704152-44223f84-90af-4c69-a2d2-3ab126705d7a.png)

**Comment by StoiaCode** [comment]
I have yet to check for sure, but what you experienced first was certainly not intended behaviour. 
Parenting (when one bone reacts to the bone it's hanging on) is not yet a thing, so all bones will move and rotate entirely on their own disregarding all other bones.
