### ISSUE TITLE
[Customize+] There was an error while loading plugin configuration

### ISSUE THREAD

**Issue by LuciferielOphelia** [XIV-Tools/CustomizePlus#88]
[Customize+] There was an error while loading plugin configuration, details have been printed into dalamud console.

I have so far tried reinstalling FF, and Dalamud. Not sure how to fix this. It opens a window still, but inside the box is a blank black square.

**Comment by StoiaCode** [comment]
Type /xllog in chat and get us that log. Without that we can't do a whole lot.

**Comment by LuciferielOphelia** [comment]
> Type /xllog in chat and get us that log. Without that we can't do a whole lot.

13:36:20.182 | INF [IME] Enabled!
13:36:20.737 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis18, 18pt, skew=0, weight=0)" has been requested.
13:36:23.284 | WRN [Penumbra] Mod at D:\FFXIV Mods\Smol or Tall - by Coco without name is not supported.
13:36:23.414 | INF [Penumbra] Rediscovered mods.
13:36:23.703 | INF [Penumbra] WebServer New State - Loading
13:36:23.715 | INF [Penumbra] WebServer New State - Listening
13:36:23.728 | INF [Penumbra] WebServer New State - Loading
13:36:23.729 | INF [Penumbra] WebServer New State - Listening
13:36:23.730 | INF [Penumbra] Penumbra Version 0.6.6.5, Commit #c958935 successfully Loaded from https://raw.githubusercontent.com/xivdev/Penumbra/master/repo.json.
13:36:23.731 | INF [Penumbra] Loading native OtterTex assembly from C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\Penumbra\0.6.6.5.
13:36:23.738 | INF [LOCALPLUGIN] Finished loading Penumbra.dll
13:36:23.739 | INF [PLUGINM] ============= LoadPluginsSync(AnytimeSync) END =============
13:36:23.739 | INF [PLUGINM] ============= LoadPluginsAsync(AnytimeAsync) START =============
13:36:23.741 | INF [PLUGINM] ============= LoadPluginsAsync(AnytimeAsync) END =============
13:36:23.741 | INF [SPL] [T3] PML OK!
13:36:23.755 | INF [PLUGINM] ============= LoadPluginsSync(FrameworkTickSync) START =============
13:36:23.755 | INF [PLUGINM] ============= LoadPluginsSync(FrameworkTickSync) END =============
13:36:23.756 | INF [PLUGINM] ============= LoadPluginsAsync(FrameworkTickAsync) START =============
13:36:23.756 | INF [PLUGINM] ============= LoadPluginsAsync(FrameworkTickAsync) END =============
13:36:23.771 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) START =============
13:36:23.771 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) END =============
13:36:23.771 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) START =============
13:36:23.772 | INF [PLUGINM] Loading plugin Mare Synchronos
13:36:23.772 | INF [PLUGINM] Loading plugin Snooper
13:36:23.772 | INF [PLUGINM] Loading plugin XIV Instant Messenger
13:36:23.772 | INF [PLUGINM] Loading plugin Peeping Tom
13:36:23.772 | INF [PLUGINM] Loading plugin MakePlace Plugin
13:36:23.772 | INF [PLUGINM] Loading plugin Honorific
13:36:23.772 | INF [PLUGINM] Loading plugin Heels Plugin
13:36:23.772 | INF [PLUGINM] Loading plugin Brio
13:36:23.772 | INF [PLUGINM] Loading plugin Penny Pincher
13:36:23.772 | INF [PLUGINM] Loading plugin VFXEditor
13:36:23.772 | INF [PLUGINM] Loading plugin Palette+
13:36:23.772 | INF [PLUGINM] Loading plugin PriceCheck
13:36:23.772 | INF [PLUGINM] Loading plugin Market board
13:36:23.772 | INF [PLUGINM] Loading plugin Glamourer
13:36:23.772 | INF [PLUGINM] Loading plugin Customize+
13:36:23.773 | INF [PLUGINM] Loading plugin XIV Combo
13:36:23.782 | INF [LOCALPLUGIN] Loading Honorific.dll
13:36:23.793 | INF [LOCALPLUGIN] Loading HeelsPlugin.dll
13:36:23.794 | INF [LOCALPLUGIN] Loading PennyPincher.dll
13:36:23.795 | INF [LOCALPLUGIN] Loading Snooper.dll
13:36:23.795 | INF [LOCALPLUGIN] Loading MarketBoardPlugin.dll
13:36:23.796 | INF [LOCALPLUGIN] Loading XIVCombo.dll
13:36:23.798 | INF [LOCALPLUGIN] Loading PalettePlus.dll
13:36:23.801 | INF [PLUGINM] Loading plugin Wordsmith
13:36:23.804 | INF [LOCALPLUGIN] Loading CustomizePlus.dll
13:36:23.812 | INF [LOCALPLUGIN] Loading PeepingTom.dll
13:36:23.838 | INF [LOCALPLUGIN] Loading MakePlacePlugin.dll
13:36:23.844 | INF [LOCALPLUGIN] Loading Brio.dll
13:36:23.845 | INF [LOCALPLUGIN] Loading Glamourer.dll
13:36:23.847 | INF [LOCALPLUGIN] Finished loading Snooper.dll
13:36:23.860 | INF [LOCALPLUGIN] Loading Wordsmith.dll
13:36:23.861 | INF [LOCALPLUGIN] Loading PriceCheck.dll
13:36:23.862 | INF [MakePlacePlugin] Hooking IsSaveLayoutDetour at 7FF645DD1440
13:36:23.890 | INF [LOCALPLUGIN] Finished loading HeelsPlugin.dll
13:36:23.872 | ERR [CustomizePlus] Unable to load plugin config
System.IO.IOException: The file 'C:\Users\donov\AppData\Roaming\XIVLauncher\pluginConfigs\CustomizePlus_v0.json' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at CustomizePlus.Util.ConfigurationManager.ConvertConfigIfNeeded(String path) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Util\ConfigurationManager.cs:line 89
   at CustomizePlus.Util.ConfigurationManager.LoadConfigurationFromFile(String path) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Util\ConfigurationManager.cs:line 42
   at CustomizePlus.Plugin..ctor(DalamudPluginInterface pluginInterface) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Plugin.cs:line 93
13:36:23.916 | ERR [CustomizePlus] Error loading config
System.NullReferenceException: Object reference not set to an instance of an object.
   at CustomizePlus.Plugin.LoadConfig(Boolean autoModeUpdate) in C:\Users\marth\source\repos\CustomizePlus\CustomizePlus\Plugin.cs:line 139
13:36:23.916 | INF [LOCALPLUGIN] Loading VFXEditor.dll
13:36:23.926 | ERR Command "/customize" is already registered.
13:36:23.928 | INF [LOCALPLUGIN] Finished loading CustomizePlus.dll
13:36:23.930 | INF [LOCALPLUGIN] Finished loading PeepingTom.dll
13:36:23.949 | INF [LOCALPLUGIN] Loading MareSynchronos.dll
13:36:23.951 | INF [VFXEditor] Write location: C:\Users\donov\AppData\Roaming\XIVLauncher\pluginConfigs\VFXEditor
13:36:23.962 | INF [VFXEditor] FreeImage TeximpNet paths: C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.7.4.1\runtimes\win-x64\native\FreeImage.dll / C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.7.4.1\runtimes\win-x86\native\FreeImage.dll
13:36:23.962 | INF [VFXEditor] FreeImage Default name: FreeImage.dll Library loaded: False
13:36:23.989 | INF [VFXEditor] FreeImage Library path: C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.7.4.1\runtimes\win-x64\native\FreeImage.dll Library loaded: True
13:36:23.991 | INF [VFXEditor] NVT TeximpNet paths: C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.7.4.1\runtimes\win-x64\native\nvtt.dll / C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.7.4.1\runtimes\win-x86\native\nvtt.dll
13:36:23.991 | INF [VFXEditor] NVT Default name: nvtt.dll Library loaded: False
13:36:24.008 | INF [VFXEditor] NVT Library path: C:\Users\donov\AppData\Roaming\XIVLauncher\installedPlugins\VFXEditor\1.7.4.1\runtimes\win-x64\native\nvtt.dll Library loaded: True
13:36:24.023 | INF [LOCALPLUGIN] Finished loading Wordsmith.dll
13:36:24.217 | ERR [Wordsmith] Error loading dictionary from web: One or more errors occurred. (Response status code does not indicate success: 304 (Not Modified).)
13:36:24.266 | INF [MareSynchronos] [     MarePlugin]{2} Launching Mare Synchronos 0.8.27
13:36:24.270 | INF [MareSynchronos] [       Lifetime]{2} Application started. Press Ctrl+C to shut down.
13:36:24.270 | INF [MareSynchronos] [       Lifetime]{2} Hosting environment: Production
13:36:24.270 | INF [MareSynchronos] [       Lifetime]{2} Content root path: C:\Users\donov\AppData\Roaming\XIVLauncher\pluginConfigs\MareSynchronos
13:36:24.275 | INF [LOCALPLUGIN] Finished loading MareSynchronos.dll
13:36:24.559 | INF [LOCALPLUGIN] Finished loading PennyPincher.dll
13:36:24.561 | INF [MakePlacePlugin] Hooking SelectItemDetour at 7FF645DCB340
13:36:24.561 | INF [LOCALPLUGIN] Finished loading Honorific.dll
13:36:24.570 | INF [LOCALPLUGIN] Finished loading XIVCombo.dll
13:36:24.619 | INF [LOCALPLUGIN] Finished loading Glamourer.dll
13:36:24.701 | INF [MakePlacePlugin] Hooking UpdateYardObj at 7FF6463281D0
13:36:24.702 | INF [LOCALPLUGIN] Finished loading PalettePlus.dll
13:36:24.706 | INF [MakePlacePlugin] Hooking GetGameObject at 7FF64632A540
13:36:24.707 | INF [MakePlacePlugin] Hooking GetObjectFromIndex at 7FF646BED1E0
13:36:24.708 | INF [LOCALPLUGIN] Finished loading PriceCheck.dll
13:36:24.709 | INF [MakePlacePlugin] Hooking GetYardIndex at 7FF646324E00
13:36:24.717 | INF [LOCALPLUGIN] Finished loading VFXEditor.dll
13:36:24.721 | INF [LOCALPLUGIN] Finished loading Brio.dll
13:36:24.747 | INF [MakePlacePlugin] Loaded 4 landset rows
13:36:24.747 | INF [MakePlacePlugin] Loaded 1309 furniture
13:36:24.747 | INF [MakePlacePlugin] Loaded 292 yard objects
13:36:24.748 | INF [MakePlacePlugin] Loaded 208 united parts
13:36:24.748 | INF [MakePlacePlugin] Loaded 121 dyes
13:36:24.748 | INF [MakePlacePlugin] Loaded 428 items with AdditionalData
13:36:24.748 | INF [MakePlacePlugin] MakePlace Plugin v2.21 initialized
13:36:24.748 | INF [LOCALPLUGIN] Finished loading MakePlacePlugin.dll
13:36:24.787 | INF [Brio] Penumbra integration initialized
13:36:24.820 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Jupiter23, 23pt, skew=0, weight=0)" has been requested.
13:36:25.369 | INF [LOCALPLUGIN] Finished loading MarketBoardPlugin.dll
13:36:25.370 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) END =============
13:36:25.370 | INF [PLUGINM] Loaded plugins on boot
13:36:25.388 | INF Saved cache to "C:\Users\donov\AppData\Roaming\XIVLauncher\addon\Hooks\7.5.0.2\cachedSigs\2023.03.24.0000.0000.json"
13:37:19.700 | INF [PLUGINM] Starting plugin update
13:37:19.701 | INF [PLUGINM] Plugin update OK.
13:37:22.260 | INF [MareSynchronos] [  ApiController]{2} Recreating Connection
13:37:23.141 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 66.056ms
13:37:23.500 | INF [MareSynchronos] [WebSoc...nsport]{2} Starting transport. Transfer mode: Binary. Url: 'wss://maresynchronos.com/mare?id=ej0TfKfmohcllvbVfoIwlQ'.
13:37:24.088 | INF [MareSynchronos] [ HttpConnection]{2} HttpConnection Started.
13:37:24.100 | INF [MareSynchronos] [  HubConnection]{2} Using HubProtocol 'messagepack v1'.
13:37:24.287 | INF [MareSynchronos] [  HubConnection]{2} HubConnection started.
13:37:25.056 | INF [MareSynchronos] [Notifi...ervice]{2} NotificationMessage { Title = Info from Lunae Crescere Incipientis (Central Server EU), Message = Welcome to Mare Synchronos "Main", Current Online Users: 16123, Type = Info, TimeShownOnScreen = 5000 }
13:37:43.822 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 51.2165ms
13:37:45.339 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 51.7306ms
13:37:46.354 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 50.0988ms
13:40:19.954 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 50.5805ms
13:40:20.955 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 50.6701ms
13:44:14.103 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 50.1838ms
13:44:15.619 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 49.7373ms
13:44:16.636 | INF [MareSynchronos] [Player...actory]{2} Building character data for Player took 49.9832ms
{ } [ Send ]

**Comment by StoiaCode** [comment]
Go to C:\Users\donov\AppData\Roaming\XIVLauncher\pluginConfigs\ and rename CustomizePlus_v0.json to 'CustomizePlus_OLD.json'.

Fixed in the next update.

**Comment by LuciferielOphelia** [comment]
> CustomizePlus_OLD.json

Thank you for your help.
