### ISSUE TITLE
Facial Scaling

### ISSUE THREAD

**Issue by Sidhenanigans** [XIV-Tools/CustomizePlus#9]
Customize is loading some crazy exaggerated facial scaling when I load any body scaling with it. None of my scaling files have facial scaling (they're all 1, 1, 1 for facial features and head), but the facial scaling seems to be proportional with breast size, from what I can tell.
I tried creating a new scaling file after Customize was updated and got the same thing.
I have the correct URL using main rather than master. I tried restarting the game after making that change as well.  Tried with and without Anamnesis running.
![Untitled](https://user-images.githubusercontent.com/91506686/170936822-2ec73ca9-f359-4be6-86a1-5ef037a52564.png)
.

**Comment by Yuki-Codes** [comment]
This has been fixed for the next release
