### ISSUE TITLE
Camera placed oddly in some cutscenes

### ISSUE THREAD

**Issue by SerraBritt** [XIV-Tools/CustomizePlus#95]
In some cutscenes, the camera seems to be offset by an amount that is related to the amount of the base bone adjustment. So far it has only happened with the Bozja weapon quests where one completes a stage of the weapon, though it suggests that it may happen with other relic-style weapons since they have similar poses.
This is the end of the quest and the camera is so far above my head that only the tips of my ears are showing when I expected to be able to see my face.
![image](https://user-images.githubusercontent.com/131739401/234249071-6c0f2a36-2516-4608-86fa-195915916f24.png)

**Comment by SerraBritt** [comment]
I realize that I forgot to mention that my character is scaled to be larger than normal, so I would have expected the camera to be below my head and not above it.

**Comment by StoiaCode** [comment]
This should be fixed now. Please reopen if it still happens.
