### ISSUE TITLE
Root fixed on Gpose

### ISSUE THREAD

**Issue by XiKav** [XIV-Tools/CustomizePlus#98]
Hello, until now I did not encounter any problem with Customize, but following an update, as soon as I enter Gpose, there is a feature that I can no longer use, it is the modification of the dimension of the character ... indeed, when I try to reduce or enlarge a character... it automatically reverts to 1, and it's problematic, knowing that I would like to benefit from the advantages of C+ AND the advantages of Anamnesis, but that I have to choose between the two.

**Comment by XiKav** [comment]
+1

**Comment by StoiaCode** [comment]
Note #84 first paragraph.
Also note that C+ intention is mostly use outside of Gpose, many features will disable itself inside gpose. 

Also please refrain from bumping your own issues.
